# ansible-playbook drogon.yml -i hosts --tags docker_apps
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass
---
- hosts: drogon
  sudo: true
  roles:
    - docker
    - docker-compose
    - mergerfs
    - snapraid
    - drogon
